services:
  app:
    container_name: go-transport-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGDATABASE=transport
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
      - DATABASE_URL=postgres://postgres:postgres@db:5432/transport?sslmode=disable
    networks:
      - transport-network
    restart: unless-stopped

  db:
    container_name: go-transport-db
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transport
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - transport-network
    restart: unless-stopped

networks:
  transport-network:
    driver: bridge

volumes:
  postgres_data: